language: python
python:
  - "3.5"
# command to install dependencies
install:
    - curl http://python-distribute.org/distribute_setup.py | sudo python3
    - curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | sudo python3
    - make install
# command to run tests
script: nosetests
sudo: required
dist: trusty
